name: Build OBS for AARCH64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libqt5x11extras5-dev libudev-dev libv4l-dev libpulse-dev libjack-jackd2-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev libavfilter-dev libcurl4-openssl-dev libfontconfig1-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev libdbus-1-dev libbz2-dev liblzma-dev libarchive-dev libgl1-mesa-dev libmbedtls-dev

      - name: Build OBS
        run: |
          mkdir build
          cd build
          cmake ..
          VERBOSE=1 make -j$(nproc)
      
      - name: Install checkinstall
        run: |
          sudo apt-get install -y checkinstall
      
      - name: Create deb package
        run: |
          cd build
          sudo checkinstall --default --pkgname=obs --pkgversion="$(git describe --abbrev=0 --tags)" --pkglicense=GPL --pakdir=../
