name: Build OBS for Linux AARCH64 with MPP support

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdrm-rockchip1 libmali-rockchip librockchip-mpp1 librockchip-vpu0 libv4l-dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build MPP
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t zxctw/mpp:latest https://github.com/rockchip-linux/mpp.git

      - name: Build OBS with MPP
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t zxctw/obs-studio:latest --build-arg MPP_PATH=./mpp .

      - name: Create deb package
        run: |
          docker run --rm -v $(pwd):/workspace zxctw/obs-studio:latest /bin/bash -c "cp /root/obs-studio/build/rpm/obs-studio-*.rpm /workspace"

      - name: Upload deb package
        uses: actions/upload-artifact@v2
        with:
          name: obs-studio-deb
          path: ./obs-studio-*.deb
