name: Build OBS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      DISPLAY: ':99'

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb pulseaudio

    - name: Set up Xvfb
      run: |
        Xvfb :99 -screen 0 1280x720x24 +extension GLX +render -noreset -nolisten tcp -nolisten unix &
        export PULSE_SERVER="tcp:localhost:9997"

    - name: Build OBS
      run: |
        git clone https://github.com/obsproject/obs-studio.git
        cd obs-studio
        mkdir build && cd build
        cmake ..
        make -j$(nproc)

    - name: Package OBS as .deb
      run: |
        mkdir -p deb-package/DEBIAN
        touch deb-package/DEBIAN/control
        echo "Package: obs-studio" >> deb-package/DEBIAN/control
        echo "Version: 1.0" >> deb-package/DEBIAN/control
        echo "Architecture: arm64" >> deb-package/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> deb-package/DEBIAN/control
        echo "Description: OBS Studio" >> deb-package/DEBIAN/control
        echo "" >> deb-package/DEBIAN/control
        dpkg-deb --build deb-package
        mv deb-package.deb obs-studio-arm64.deb

    - name: Upload OBS .deb file
      uses: actions/upload-artifact@v2
      with:
        name: obs-studio-arm64.deb
        path: obs-studio-arm64.deb
