name: Build OBS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    
    - name: Build OBS
      run: |
        git clone https://github.com/obsproject/obs-studio.git
        cd obs-studio
        docker buildx build --file Dockerfile --platform linux/arm64 -t myusername/obs-studio:latest .
    
    - name: Package OBS as .deb
      run: |
        mkdir -p deb-package/DEBIAN
        touch deb-package/DEBIAN/control
        echo "Package: obs-studio" >> deb-package/DEBIAN/control
        echo "Version: 1.0" >> deb-package/DEBIAN/control
        echo "Architecture: arm64" >> deb-package/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> deb-package/DEBIAN/control
        echo "Description: OBS Studio" >> deb-package/DEBIAN/control
        echo "" >> deb-package/DEBIAN/control
        dpkg-deb --build deb-package
        mv deb-package.deb obs-studio-arm64.deb
    
    - name: Upload OBS .deb file
      uses: actions/upload-artifact@v2
      with:
        name: obs-studio-arm64.deb
        path: obs-studio-arm64.deb
